apiVersion: v2
name: rengage-ce
description: A Helm chart for deploying Rengage CE (Community Edition)
home: https://rengage.ai/
icon: https://rengage.ai/img/logo.svg

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# dependencies:
#   - name: kube-prometheus-stack
#     version: "74.0.*"
#     repository: https://prometheus-community.github.io/helm-charts
#     condition: kube-prometheus-stack.enabled

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
