apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-data-retention" (include "rengage-ce.fullname" .) }}
  labels:
    {{- include "rengage-ce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.data-retention.service.type }}
  ports:
    - port: {{ .Values.data-retention.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rengage-ce.selectorLabels" . | nindent 4 }}
