apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ai-agent" (include "rengage-ce.fullname" .) }}
  labels:
    {{- include "rengage-ce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ai-agent.service.type }}
  ports:
    - port: {{ .Values.ai-agent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rengage-ce.selectorLabels" . | nindent 4 }}
